unit res;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, ExtCtrls;

type
  TForm2 = class(TForm)
    sb: TImage;
    ab: TImage;
    sa: TImage;
    br: TImage;
    d: TImage;
    bgn: TImage;
    agn: TImage;
    ar: TImage;
    bb: TImage;
    ap: TImage;
    bgr: TImage;
    bp: TImage;
    agr: TImage;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form2: TForm2;

implementation

{$R *.dfm}

end.
